spring:
  application:
    name: kafka-producer
  cloud:
    stream:
      bindings:
        stream-demo-output:
          destination: STREAM_DEMO_TOPIC
          content-type: application/json
      kafka:
        binder:
          brokers: 172.16.0.191:34991
        bindings:
          stream-demo-output:
            producer:
              sync: true
server:
  port: 20000